spring:
   cloud:
       config:
          server:
             git:
                uri: https://github.com/MinhTranQuang258/spring-cloud-config.git
   config:
       name: configserver 
server:
   port: 8888
management:
   security:
       enabled: false
